name:                sample-haskell
version:             0.1.0.0
github:              "ju113n/sample-haskell"
license:             BSD3
author:              "Julien Lebrun"
maintainer:          "jl@exanet.nz"
copyright:           "Julien Lebrun"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            sample

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ju113n/sample-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- http-types
- sqlite-simple
- text
- time
- wai
- warp

default-extensions:
- OverloadedStrings

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wno-name-shadowing
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  sample-haskell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample-haskell

tests:
  sample-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sample-haskell
